# Generated by Django 4.2 on 2023-06-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=256)),
                ('is_god', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
